AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  StopEC2Instances:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: StopEC2Instances
      Description: ''
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: 'arn:aws:iam::007786019690:role/lambda_instance_auto'
      Runtime: python3.7
      Timeout: 10
